apiVersion: apps/v1
kind: Deployment                  # Kubernetes controller objects
metadata:
  name: aresworld        # Pod name
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: aresworld        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: aresworld
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: aresworld
        image: fliropp/aresworld:latest
        imagePullPolicy: Always
        args: ["server"]
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on
---
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: aresworld-service   # Name of the resource
spec:
  type: NodePort                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: aresworld
